PROXY_CLUSTER_STRATEGY=kubernetes-dns
PROXY_HEADLESS_SERVICE=proxy-headless-svc
PROXY_APP_NAME=proxy
PROXY_CLUSTER_POLLING=3000
PROXY_HEARTBEAT_INTERVAL=240_000
PROXY_HTTP_PORT=9001
PROXY_PORT=9000
PROXY_UDS_ADDRESS=false
PROXY_UDS_MODE=/var/run/cloudstate.sock
USER_FUNCTION_HOST=127.0.0.1
USER_FUNCTION_PORT=8080
NODE_COOKIE=6eycE1E/S341t4Bcto262ffyFWklCWHQIKloJDJYR7Y=